### ISSUE TITLE
Some todo items

### ISSUE THREAD

**Issue by yuichiu416** [chinweenie/modern#22]
- [x] 1. After creating a new story, the home page doesn't render the new story automatically
- [x] 2. Edit profile page is empty, haven't worked on it yet.
![image](https://user-images.githubusercontent.com/25892843/65476354-39c90e00-de48-11e9-8dbc-e4838cd48a14.png)
- [x] 3. In the profile dropdown, no profile picture
- [x] 4. When expand the search input field, the align is a little bit weird
- [x] 5. `story === undefined` after refresh on story show page
- [x] 6. no cursor change when hovering over the links on the home page
- [x] 7. style nav bar profile picture

**Comment by chinweenie** [comment]
Done with all the list items
